name: llvm_project
on: workflow_dispatch

jobs:
  llvm_clang_lld_polly-x86_64-msvc-release:
    runs-on: windows-2022
    env:
      LLVM_VERSION: '14.0.6'
      PYTHON_VERSION: '3.10.5'
      Z3_VERSION: '4.10.2'
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Create artifacts directory
        shell: pwsh
        run: |
          pushd .
          cd \
          $llvm_artifacts_root = mkdir llvm+clang+lld+polly-${{ env.LLVM_VERSION }}-x86_64-msvc-release
          "LLVM_ARTIFACTS_ROOT=${llvm_artifacts_root}" >> $env:GITHUB_ENV
          popd
      - name: Update vcpkg
        shell: pwsh
        run: |
          pushd .
          cd ${env:VCPKG_INSTALLATION_ROOT}
          git pull
          popd
      - name: Install zlib from vcpkg
        shell: pwsh
        run: |
          vcpkg install zlib:x64-windows-static-md
      - name: Install libxml2 from vcpkg
        shell: pwsh
        run: |
          vcpkg install libxml2:x64-windows-static-md
      - name: Download z3-solver
        shell: pwsh
        run: |
          curl -L -O 'https://github.com/Z3Prover/z3/releases/download/z3-${{ env.Z3_VERSION }}/z3-${{ env.Z3_VERSION }}-x64-win.zip'
          
          7z x z3-${{ env.Z3_VERSION }}-x64-win.zip
          rm z3-${{ env.Z3_VERSION }}-x64-win.zip
          
          "Z3_ARTIFACTS_ROOT=${PWD}\z3-${{ env.Z3_VERSION }}-x64-win" >> $env:GITHUB_ENV
      - name: Clone llvm-project
        shell: pwsh
        run: |
          git clone -b llvmorg-${{ env.LLVM_VERSION }} --depth 1 https://github.com/llvm/llvm-project.git
          git apply --verbose --directory=llvm-project .\patches\llvm-project\0001-fix-LLVMSupport-z3-link-path.patch
      - name: Build llvm+clang+lld+polly
        shell: pwsh
        run: |
          pushd .
          $env:PATH += ";${{ env.Z3_ARTIFACTS_ROOT }}\bin"
          cd llvm-project
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" `
            -A x64 `
            -Thost=x64 `
            '-DCMAKE_BUILD_TYPE=Release' `
            "-DCMAKE_TOOLCHAIN_FILE=${env:VCPKG_INSTALLATION_ROOT}\scripts\buildsystems\vcpkg.cmake".Replace('\', '/') `
            '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md' `
            "-DCMAKE_EXE_LINKER_FLAGS=/LIBPATH:${{ env.Z3_ARTIFACTS_ROOT }}\bin".Replace('\', '/') `
            "-DCMAKE_SHARED_LINKER_FLAGS=/LIBPATH:${{ env.Z3_ARTIFACTS_ROOT }}\bin".Replace('\', '/') `
            "-DCMAKE_PREFIX_PATH=${{ env.Z3_ARTIFACTS_ROOT }};${{ env.LLVM_ARTIFACTS_ROOT }}".Replace('\', '/') `
            "-DCMAKE_INSTALL_PREFIX=${{ env.LLVM_ARTIFACTS_ROOT }}".Replace('\', '/') `
            '-DLLVM_ENABLE_PROJECTS=clang;lld;polly' `
            '-DLLVM_ENABLE_ZLIB=FORCE_ON' `
            '-DLLVM_ENABLE_LIBXML2=FORCE_ON' `
            '-DLLVM_ENABLE_Z3_SOLVER=ON' `
            ..\llvm
          cmake --build . --config Release --target install
          popd
      - name: Copy libz3 to artifacts directory
        shell: pwsh
        run: |
          cp '${{ env.Z3_ARTIFACTS_ROOT }}\bin\libz3.dll' '${{ env.LLVM_ARTIFACTS_ROOT }}\bin'
          cp '${{ env.Z3_ARTIFACTS_ROOT }}\bin\libz3.lib' '${{ env.LLVM_ARTIFACTS_ROOT }}\lib'
      - name: Pack artifacts
        shell: pwsh
        # pack artifacts to preserve symbol-links
        run: |
          pushd .
          $llvm_artifacts_dirname = Split-Path '${{ env.LLVM_ARTIFACTS_ROOT }}' -Parent
          $llvm_artifacts_basename = Split-Path '${{ env.LLVM_ARTIFACTS_ROOT }}' -Leaf
          cd ${llvm_artifacts_dirname}
          tar -czvf "${llvm_artifacts_basename}.tar.gz" "${llvm_artifacts_basename}"
          popd
          mv "${llvm_artifacts_dirname}\${llvm_artifacts_basename}.tar.gz" .\
          "LLVM_ARTIFACTS_TARBALL=${llvm_artifacts_basename}.tar.gz" >> $env:GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LLVM_ARTIFACTS_TARBALL }}
          path: ${{ env.LLVM_ARTIFACTS_TARBALL }}
